import RequireAuthentication from '@/components/RequireAuthentication'
import './globals.css'
import NavBar from './NavBar'
import MongoClientServiceProvider from '@/components/MongoClientServiceProvider'
import clientPromise from '../../lib/mongodb'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MongoClientServiceProvider clientService={clientPromise}>
          <NavBar />
          <main className='dark:bg-stone-900 dark:text-red-400 min-h-screen'>
            <RequireAuthentication>
              {children}
            </RequireAuthentication>
          </main>
        </MongoClientServiceProvider>
      </body>
    </html>
  )
}
